function BenefitsTracking() {
  return (
    <div className="dashboard-wrapper">
      <h2>Benefits Tracking</h2>
      <p>Track business benefits, cost savings, and ROI generated by active projects.</p>
    </div>
  );
}

export default BenefitsTracking;
